package com.xiyunmn.puredupan.hook.config.model

enum class MarketingPopup(val key: String) {
    OPERATION_IMAGE(FeatureKeys.KEY_BLOCK_IN_APP_DIALOG),
    OPERATION_ANIMATION(FeatureKeys.KEY_BLOCK_POPUP_OPERATION_ANIMATION),
    OPERATION_AFX(FeatureKeys.KEY_BLOCK_POPUP_OPERATION_AFX),
    NEW_USER_OFFER(FeatureKeys.KEY_BLOCK_POPUP_NEW_USER_OFFER),
    NEW_USER_REWARD(FeatureKeys.KEY_BLOCK_POPUP_NEW_USER_REWARD),
    NEW_USER_REWARD_V2(FeatureKeys.KEY_BLOCK_POPUP_NEW_USER_REWARD_V2),
    COIN_PROMOTION(FeatureKeys.KEY_BLOCK_POPUP_COIN_PROMOTION),
    COUPON_GIFT_V3(FeatureKeys.KEY_BLOCK_POPUP_COUPON_GIFT_V3),
    COUPON_GIFT_V2(FeatureKeys.KEY_BLOCK_POPUP_COUPON_GIFT_V2),
    LIFE_COUPON(FeatureKeys.KEY_BLOCK_POPUP_LIFE_COUPON),
    LIFE_PRODUCT(FeatureKeys.KEY_BLOCK_POPUP_LIFE_PRODUCT),
    LIFE_PRODUCT_V3(FeatureKeys.KEY_BLOCK_POPUP_LIFE_PRODUCT_V3),
    LIFE_V10(FeatureKeys.KEY_BLOCK_POPUP_LIFE_V10),
    LIFE_V10_REPURCHASE(FeatureKeys.KEY_BLOCK_POPUP_LIFE_V10_REPURCHASE),
    LIFE_COMBO(FeatureKeys.KEY_BLOCK_POPUP_LIFE_COMBO),
    LIFE_LIMITED(FeatureKeys.KEY_BLOCK_POPUP_LIFE_LIMITED),
    LIFE_RETENTION(FeatureKeys.KEY_BLOCK_POPUP_LIFE_RETENTION),
    LIFE_PRICE_UPGRADE(FeatureKeys.KEY_BLOCK_POPUP_LIFE_PRICE_UPGRADE),
    OVERDUE_UNION(FeatureKeys.KEY_BLOCK_POPUP_OVERDUE_UNION),
    OVERDUE_COUPON(FeatureKeys.KEY_BLOCK_POPUP_OVERDUE_COUPON),
    OVERDUE_PRODUCT(FeatureKeys.KEY_BLOCK_POPUP_OVERDUE_PRODUCT),
    MY_PAGE_OFFER(FeatureKeys.KEY_BLOCK_POPUP_MY_PAGE_OFFER),
    INCENTIVE_ENTRANCE(FeatureKeys.KEY_BLOCK_POPUP_INCENTIVE_ENTRANCE),
    INCENTIVE_GUIDE(FeatureKeys.KEY_BLOCK_POPUP_INCENTIVE_GUIDE),
    INCENTIVE_NEXT(FeatureKeys.KEY_BLOCK_POPUP_INCENTIVE_NEXT),
    FREE_MODE(FeatureKeys.KEY_BLOCK_POPUP_FREE_MODE),
    FREE_MODE_NEW(FeatureKeys.KEY_BLOCK_POPUP_FREE_MODE_NEW),
    FREE_MODE_FLOAT(FeatureKeys.KEY_BLOCK_POPUP_FREE_MODE_FLOAT),
    MIGHTY_MARKETING(FeatureKeys.KEY_BLOCK_POPUP_MIGHTY_MARKETING),
    MODERATE_MARKETING(FeatureKeys.KEY_BLOCK_POPUP_MODERATE_MARKETING),
    SEARCH_MEMBERSHIP(FeatureKeys.KEY_BLOCK_POPUP_SEARCH_MEMBERSHIP),
    TRANSFER_COUPON(FeatureKeys.KEY_BLOCK_POPUP_TRANSFER_COUPON),
    TRANSFER_LIMIT(FeatureKeys.KEY_BLOCK_POPUP_TRANSFER_LIMIT),
    TRANSFER_SPACE(FeatureKeys.KEY_BLOCK_POPUP_TRANSFER_SPACE);

    companion object {
        fun savedValue(key: String, contains: (String) -> Boolean, read: (String) -> Boolean): Boolean {
            if (key == COUPON_GIFT_V3.key && !contains(key)) {
                return read(FeatureKeys.KEY_BLOCK_IN_APP_DIALOG)
            }
            return read(key)
        }
    }
}
